// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: splitter.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_splitter_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_splitter_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_splitter_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_splitter_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_splitter_2eproto;
namespace splitter {
class Command;
struct CommandDefaultTypeInternal;
extern CommandDefaultTypeInternal _Command_default_instance_;
class Envelope;
struct EnvelopeDefaultTypeInternal;
extern EnvelopeDefaultTypeInternal _Envelope_default_instance_;
class FFTReport;
struct FFTReportDefaultTypeInternal;
extern FFTReportDefaultTypeInternal _FFTReport_default_instance_;
}  // namespace splitter
PROTOBUF_NAMESPACE_OPEN
template<> ::splitter::Command* Arena::CreateMaybeMessage<::splitter::Command>(Arena*);
template<> ::splitter::Envelope* Arena::CreateMaybeMessage<::splitter::Envelope>(Arena*);
template<> ::splitter::FFTReport* Arena::CreateMaybeMessage<::splitter::FFTReport>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace splitter {

enum Command_Type : int {
  Command_Type_UNKNOWN = 0,
  Command_Type_START = 1,
  Command_Type_STOP = 2,
  Command_Type_SET_PORT_ENABLED = 3,
  Command_Type_Command_Type_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  Command_Type_Command_Type_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool Command_Type_IsValid(int value);
constexpr Command_Type Command_Type_Type_MIN = Command_Type_UNKNOWN;
constexpr Command_Type Command_Type_Type_MAX = Command_Type_SET_PORT_ENABLED;
constexpr int Command_Type_Type_ARRAYSIZE = Command_Type_Type_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* Command_Type_descriptor();
template<typename T>
inline const std::string& Command_Type_Name(T enum_t_value) {
  static_assert(::std::is_same<T, Command_Type>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function Command_Type_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    Command_Type_descriptor(), enum_t_value);
}
inline bool Command_Type_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, Command_Type* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<Command_Type>(
    Command_Type_descriptor(), name, value);
}
// ===================================================================

class FFTReport final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:splitter.FFTReport) */ {
 public:
  inline FFTReport() : FFTReport(nullptr) {}
  ~FFTReport() override;
  explicit PROTOBUF_CONSTEXPR FFTReport(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  FFTReport(const FFTReport& from);
  FFTReport(FFTReport&& from) noexcept
    : FFTReport() {
    *this = ::std::move(from);
  }

  inline FFTReport& operator=(const FFTReport& from) {
    CopyFrom(from);
    return *this;
  }
  inline FFTReport& operator=(FFTReport&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const FFTReport& default_instance() {
    return *internal_default_instance();
  }
  static inline const FFTReport* internal_default_instance() {
    return reinterpret_cast<const FFTReport*>(
               &_FFTReport_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(FFTReport& a, FFTReport& b) {
    a.Swap(&b);
  }
  inline void Swap(FFTReport* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(FFTReport* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  FFTReport* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<FFTReport>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const FFTReport& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const FFTReport& from) {
    FFTReport::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(FFTReport* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "splitter.FFTReport";
  }
  protected:
  explicit FFTReport(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kCenterMhzFieldNumber = 1,
  };
  // float center_mhz = 1;
  void clear_center_mhz();
  float center_mhz() const;
  void set_center_mhz(float value);
  private:
  float _internal_center_mhz() const;
  void _internal_set_center_mhz(float value);
  public:

  // @@protoc_insertion_point(class_scope:splitter.FFTReport)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    float center_mhz_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_splitter_2eproto;
};
// -------------------------------------------------------------------

class Command final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:splitter.Command) */ {
 public:
  inline Command() : Command(nullptr) {}
  ~Command() override;
  explicit PROTOBUF_CONSTEXPR Command(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Command(const Command& from);
  Command(Command&& from) noexcept
    : Command() {
    *this = ::std::move(from);
  }

  inline Command& operator=(const Command& from) {
    CopyFrom(from);
    return *this;
  }
  inline Command& operator=(Command&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Command& default_instance() {
    return *internal_default_instance();
  }
  static inline const Command* internal_default_instance() {
    return reinterpret_cast<const Command*>(
               &_Command_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(Command& a, Command& b) {
    a.Swap(&b);
  }
  inline void Swap(Command* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Command* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Command* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Command>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Command& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Command& from) {
    Command::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Command* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "splitter.Command";
  }
  protected:
  explicit Command(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  typedef Command_Type Type;
  static constexpr Type UNKNOWN =
    Command_Type_UNKNOWN;
  static constexpr Type START =
    Command_Type_START;
  static constexpr Type STOP =
    Command_Type_STOP;
  static constexpr Type SET_PORT_ENABLED =
    Command_Type_SET_PORT_ENABLED;
  static inline bool Type_IsValid(int value) {
    return Command_Type_IsValid(value);
  }
  static constexpr Type Type_MIN =
    Command_Type_Type_MIN;
  static constexpr Type Type_MAX =
    Command_Type_Type_MAX;
  static constexpr int Type_ARRAYSIZE =
    Command_Type_Type_ARRAYSIZE;
  static inline const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor*
  Type_descriptor() {
    return Command_Type_descriptor();
  }
  template<typename T>
  static inline const std::string& Type_Name(T enum_t_value) {
    static_assert(::std::is_same<T, Type>::value ||
      ::std::is_integral<T>::value,
      "Incorrect type passed to function Type_Name.");
    return Command_Type_Name(enum_t_value);
  }
  static inline bool Type_Parse(::PROTOBUF_NAMESPACE_ID::ConstStringParam name,
      Type* value) {
    return Command_Type_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  enum : int {
    kTypeFieldNumber = 1,
    kPortFieldNumber = 2,
    kEnableFieldNumber = 3,
  };
  // .splitter.Command.Type type = 1;
  void clear_type();
  ::splitter::Command_Type type() const;
  void set_type(::splitter::Command_Type value);
  private:
  ::splitter::Command_Type _internal_type() const;
  void _internal_set_type(::splitter::Command_Type value);
  public:

  // uint32 port = 2;
  void clear_port();
  uint32_t port() const;
  void set_port(uint32_t value);
  private:
  uint32_t _internal_port() const;
  void _internal_set_port(uint32_t value);
  public:

  // bool enable = 3;
  void clear_enable();
  bool enable() const;
  void set_enable(bool value);
  private:
  bool _internal_enable() const;
  void _internal_set_enable(bool value);
  public:

  // @@protoc_insertion_point(class_scope:splitter.Command)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    int type_;
    uint32_t port_;
    bool enable_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_splitter_2eproto;
};
// -------------------------------------------------------------------

class Envelope final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:splitter.Envelope) */ {
 public:
  inline Envelope() : Envelope(nullptr) {}
  ~Envelope() override;
  explicit PROTOBUF_CONSTEXPR Envelope(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Envelope(const Envelope& from);
  Envelope(Envelope&& from) noexcept
    : Envelope() {
    *this = ::std::move(from);
  }

  inline Envelope& operator=(const Envelope& from) {
    CopyFrom(from);
    return *this;
  }
  inline Envelope& operator=(Envelope&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Envelope& default_instance() {
    return *internal_default_instance();
  }
  enum PayloadCase {
    kReport = 1,
    kCommand = 2,
    PAYLOAD_NOT_SET = 0,
  };

  static inline const Envelope* internal_default_instance() {
    return reinterpret_cast<const Envelope*>(
               &_Envelope_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(Envelope& a, Envelope& b) {
    a.Swap(&b);
  }
  inline void Swap(Envelope* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Envelope* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Envelope* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Envelope>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Envelope& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Envelope& from) {
    Envelope::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Envelope* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "splitter.Envelope";
  }
  protected:
  explicit Envelope(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kCrc32FieldNumber = 3,
    kReportFieldNumber = 1,
    kCommandFieldNumber = 2,
  };
  // uint32 crc32 = 3;
  void clear_crc32();
  uint32_t crc32() const;
  void set_crc32(uint32_t value);
  private:
  uint32_t _internal_crc32() const;
  void _internal_set_crc32(uint32_t value);
  public:

  // .splitter.FFTReport report = 1;
  bool has_report() const;
  private:
  bool _internal_has_report() const;
  public:
  void clear_report();
  const ::splitter::FFTReport& report() const;
  PROTOBUF_NODISCARD ::splitter::FFTReport* release_report();
  ::splitter::FFTReport* mutable_report();
  void set_allocated_report(::splitter::FFTReport* report);
  private:
  const ::splitter::FFTReport& _internal_report() const;
  ::splitter::FFTReport* _internal_mutable_report();
  public:
  void unsafe_arena_set_allocated_report(
      ::splitter::FFTReport* report);
  ::splitter::FFTReport* unsafe_arena_release_report();

  // .splitter.Command command = 2;
  bool has_command() const;
  private:
  bool _internal_has_command() const;
  public:
  void clear_command();
  const ::splitter::Command& command() const;
  PROTOBUF_NODISCARD ::splitter::Command* release_command();
  ::splitter::Command* mutable_command();
  void set_allocated_command(::splitter::Command* command);
  private:
  const ::splitter::Command& _internal_command() const;
  ::splitter::Command* _internal_mutable_command();
  public:
  void unsafe_arena_set_allocated_command(
      ::splitter::Command* command);
  ::splitter::Command* unsafe_arena_release_command();

  void clear_payload();
  PayloadCase payload_case() const;
  // @@protoc_insertion_point(class_scope:splitter.Envelope)
 private:
  class _Internal;
  void set_has_report();
  void set_has_command();

  inline bool has_payload() const;
  inline void clear_has_payload();

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    uint32_t crc32_;
    union PayloadUnion {
      constexpr PayloadUnion() : _constinit_{} {}
        ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized _constinit_;
      ::splitter::FFTReport* report_;
      ::splitter::Command* command_;
    } payload_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    uint32_t _oneof_case_[1];

  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_splitter_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// FFTReport

// float center_mhz = 1;
inline void FFTReport::clear_center_mhz() {
  _impl_.center_mhz_ = 0;
}
inline float FFTReport::_internal_center_mhz() const {
  return _impl_.center_mhz_;
}
inline float FFTReport::center_mhz() const {
  // @@protoc_insertion_point(field_get:splitter.FFTReport.center_mhz)
  return _internal_center_mhz();
}
inline void FFTReport::_internal_set_center_mhz(float value) {
  
  _impl_.center_mhz_ = value;
}
inline void FFTReport::set_center_mhz(float value) {
  _internal_set_center_mhz(value);
  // @@protoc_insertion_point(field_set:splitter.FFTReport.center_mhz)
}

// -------------------------------------------------------------------

// Command

// .splitter.Command.Type type = 1;
inline void Command::clear_type() {
  _impl_.type_ = 0;
}
inline ::splitter::Command_Type Command::_internal_type() const {
  return static_cast< ::splitter::Command_Type >(_impl_.type_);
}
inline ::splitter::Command_Type Command::type() const {
  // @@protoc_insertion_point(field_get:splitter.Command.type)
  return _internal_type();
}
inline void Command::_internal_set_type(::splitter::Command_Type value) {
  
  _impl_.type_ = value;
}
inline void Command::set_type(::splitter::Command_Type value) {
  _internal_set_type(value);
  // @@protoc_insertion_point(field_set:splitter.Command.type)
}

// uint32 port = 2;
inline void Command::clear_port() {
  _impl_.port_ = 0u;
}
inline uint32_t Command::_internal_port() const {
  return _impl_.port_;
}
inline uint32_t Command::port() const {
  // @@protoc_insertion_point(field_get:splitter.Command.port)
  return _internal_port();
}
inline void Command::_internal_set_port(uint32_t value) {
  
  _impl_.port_ = value;
}
inline void Command::set_port(uint32_t value) {
  _internal_set_port(value);
  // @@protoc_insertion_point(field_set:splitter.Command.port)
}

// bool enable = 3;
inline void Command::clear_enable() {
  _impl_.enable_ = false;
}
inline bool Command::_internal_enable() const {
  return _impl_.enable_;
}
inline bool Command::enable() const {
  // @@protoc_insertion_point(field_get:splitter.Command.enable)
  return _internal_enable();
}
inline void Command::_internal_set_enable(bool value) {
  
  _impl_.enable_ = value;
}
inline void Command::set_enable(bool value) {
  _internal_set_enable(value);
  // @@protoc_insertion_point(field_set:splitter.Command.enable)
}

// -------------------------------------------------------------------

// Envelope

// .splitter.FFTReport report = 1;
inline bool Envelope::_internal_has_report() const {
  return payload_case() == kReport;
}
inline bool Envelope::has_report() const {
  return _internal_has_report();
}
inline void Envelope::set_has_report() {
  _impl_._oneof_case_[0] = kReport;
}
inline void Envelope::clear_report() {
  if (_internal_has_report()) {
    if (GetArenaForAllocation() == nullptr) {
      delete _impl_.payload_.report_;
    }
    clear_has_payload();
  }
}
inline ::splitter::FFTReport* Envelope::release_report() {
  // @@protoc_insertion_point(field_release:splitter.Envelope.report)
  if (_internal_has_report()) {
    clear_has_payload();
    ::splitter::FFTReport* temp = _impl_.payload_.report_;
    if (GetArenaForAllocation() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    _impl_.payload_.report_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::splitter::FFTReport& Envelope::_internal_report() const {
  return _internal_has_report()
      ? *_impl_.payload_.report_
      : reinterpret_cast< ::splitter::FFTReport&>(::splitter::_FFTReport_default_instance_);
}
inline const ::splitter::FFTReport& Envelope::report() const {
  // @@protoc_insertion_point(field_get:splitter.Envelope.report)
  return _internal_report();
}
inline ::splitter::FFTReport* Envelope::unsafe_arena_release_report() {
  // @@protoc_insertion_point(field_unsafe_arena_release:splitter.Envelope.report)
  if (_internal_has_report()) {
    clear_has_payload();
    ::splitter::FFTReport* temp = _impl_.payload_.report_;
    _impl_.payload_.report_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void Envelope::unsafe_arena_set_allocated_report(::splitter::FFTReport* report) {
  clear_payload();
  if (report) {
    set_has_report();
    _impl_.payload_.report_ = report;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:splitter.Envelope.report)
}
inline ::splitter::FFTReport* Envelope::_internal_mutable_report() {
  if (!_internal_has_report()) {
    clear_payload();
    set_has_report();
    _impl_.payload_.report_ = CreateMaybeMessage< ::splitter::FFTReport >(GetArenaForAllocation());
  }
  return _impl_.payload_.report_;
}
inline ::splitter::FFTReport* Envelope::mutable_report() {
  ::splitter::FFTReport* _msg = _internal_mutable_report();
  // @@protoc_insertion_point(field_mutable:splitter.Envelope.report)
  return _msg;
}

// .splitter.Command command = 2;
inline bool Envelope::_internal_has_command() const {
  return payload_case() == kCommand;
}
inline bool Envelope::has_command() const {
  return _internal_has_command();
}
inline void Envelope::set_has_command() {
  _impl_._oneof_case_[0] = kCommand;
}
inline void Envelope::clear_command() {
  if (_internal_has_command()) {
    if (GetArenaForAllocation() == nullptr) {
      delete _impl_.payload_.command_;
    }
    clear_has_payload();
  }
}
inline ::splitter::Command* Envelope::release_command() {
  // @@protoc_insertion_point(field_release:splitter.Envelope.command)
  if (_internal_has_command()) {
    clear_has_payload();
    ::splitter::Command* temp = _impl_.payload_.command_;
    if (GetArenaForAllocation() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    _impl_.payload_.command_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::splitter::Command& Envelope::_internal_command() const {
  return _internal_has_command()
      ? *_impl_.payload_.command_
      : reinterpret_cast< ::splitter::Command&>(::splitter::_Command_default_instance_);
}
inline const ::splitter::Command& Envelope::command() const {
  // @@protoc_insertion_point(field_get:splitter.Envelope.command)
  return _internal_command();
}
inline ::splitter::Command* Envelope::unsafe_arena_release_command() {
  // @@protoc_insertion_point(field_unsafe_arena_release:splitter.Envelope.command)
  if (_internal_has_command()) {
    clear_has_payload();
    ::splitter::Command* temp = _impl_.payload_.command_;
    _impl_.payload_.command_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void Envelope::unsafe_arena_set_allocated_command(::splitter::Command* command) {
  clear_payload();
  if (command) {
    set_has_command();
    _impl_.payload_.command_ = command;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:splitter.Envelope.command)
}
inline ::splitter::Command* Envelope::_internal_mutable_command() {
  if (!_internal_has_command()) {
    clear_payload();
    set_has_command();
    _impl_.payload_.command_ = CreateMaybeMessage< ::splitter::Command >(GetArenaForAllocation());
  }
  return _impl_.payload_.command_;
}
inline ::splitter::Command* Envelope::mutable_command() {
  ::splitter::Command* _msg = _internal_mutable_command();
  // @@protoc_insertion_point(field_mutable:splitter.Envelope.command)
  return _msg;
}

// uint32 crc32 = 3;
inline void Envelope::clear_crc32() {
  _impl_.crc32_ = 0u;
}
inline uint32_t Envelope::_internal_crc32() const {
  return _impl_.crc32_;
}
inline uint32_t Envelope::crc32() const {
  // @@protoc_insertion_point(field_get:splitter.Envelope.crc32)
  return _internal_crc32();
}
inline void Envelope::_internal_set_crc32(uint32_t value) {
  
  _impl_.crc32_ = value;
}
inline void Envelope::set_crc32(uint32_t value) {
  _internal_set_crc32(value);
  // @@protoc_insertion_point(field_set:splitter.Envelope.crc32)
}

inline bool Envelope::has_payload() const {
  return payload_case() != PAYLOAD_NOT_SET;
}
inline void Envelope::clear_has_payload() {
  _impl_._oneof_case_[0] = PAYLOAD_NOT_SET;
}
inline Envelope::PayloadCase Envelope::payload_case() const {
  return Envelope::PayloadCase(_impl_._oneof_case_[0]);
}
#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace splitter

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::splitter::Command_Type> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::splitter::Command_Type>() {
  return ::splitter::Command_Type_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_splitter_2eproto
