name: Splitter CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure
        run: cmake -S . -B build
      - name: Build
        run: cmake --build build
      - name: Build MCU
        run: |
          cmake -S src/stm32 -B build-stm32
          cmake --build build-stm32
      - name: Build webpage
        run: npx -p esbuild esbuild web/port-status.component.ts --bundle --outfile=web/port-status.bundle.js --external:@angular/core --external:@angular/common/http
      - name: Run
        run: ./build/splitter
